include:
  - board: akdk_bt1
    shield: kod_01_left
  - board: akdk_bt1
    shield: kod_01_right
#    snippet: studio-rpc-usb-uart
#    cmake-args: -DCONFIG_ZMK_STUDIO=y
#  - board: akdk_bt1
#    shield: settings_reset
